// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cnfwtfpvkmwktdfnsaym.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNuZnd0ZnB2a213a3RkZm5zYXltIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc3ODcxMjIsImV4cCI6MjA1MzM2MzEyMn0.keAoecg8pWJT21BVcyt8oad-PJ4ZVT1EoIAw0gw616Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);